name: Discord Notification

on:
  push:
    branches:
      - main
      - testing  # nebo jiná větev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: cschleiden/github-action-discord-webhook@v1
        with:
          url: ${{ secrets.DC_WEBHOOK_URL }}
          message: '**User:** ${{ github.actor }}\n**Commit Message:** ${{ github.event.head_commit.message }}'

