name: Build and push to TdA
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: env
        run: |
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
          echo CHANNEL_ID=${{ secrets.CHANNEL_ID }} >> .env

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v6.8.0
        with:
          context: ./
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: tda_citrak_guys:latest
          outputs: type=docker,dest=/tmp/tda_citrak_guys.tar

      - name: Upload to TdA
        uses: Tour-de-App/upload-app@tda-25
        with:
          team_token: ${{ secrets.TEAM_TOKEN }}
          image_name: tda_citrak_guys
          image_path: /tmp/tda_citrak_guys.tar
